WHMCAngularJS/Controllers/ApartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using Repositories;
using WHMCAngularJS.ViewModel;

namespace WHMCAngularJs.Controllers
{
    public class ApartmentController : Controller
    {
        Repositories.IApartmentRepository _apartmentRepository = null;
        
        public ApartmentController(IApartmentRepository apartmentRepository)
        {
            _apartmentRepository = apartmentRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetByPage(int pageNumber, int pageSize)
        {
            List<DTO.Apartment> apartmentList = null;
            int recordsTotal = 0;
            try
            {
                apartmentList = _apartmentRepository.GetAll(pageNumber, pageSize);
                recordsTotal = _apartmentRepository.ApartmentCount();
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
            return Json(new
            {
                recordsTotal,
                apartmentList
            });
        }

        public JsonResult GetAll()
        {
            List<Apartment> list = _apartmentRepository.GetAll();
            return Json(list.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetApartmentList()
        {
            List<Apartment> list = _apartmentRepository.GetApartmentList();
            return Json(list.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Get(int id)
        {
            var apartment = _apartmentRepository.Get(id);
            return Json(new { apartment = apartment, success = true, errorMessage = "" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(int id)
        {
            var result = _apartmentRepository.Delete(id);

            return Json(new
            {
                success = result,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add( Apartment  apartment)
        {
            int id = _apartmentRepository.Add( apartment);

            return Json(new
            {
                success = id > 0 ? true : false,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Update( Apartment  apartment)
        {
            bool result = _apartmentRepository.Update( apartment);
            return Json(new
            {
                success = result,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

    }

}

WHMCAngularJS/Controllers/EstateAgentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using Repositories;
using WHMCAngularJS.ViewModel;

namespace WHMCAngularJs.Controllers
{
    public class EstateAgentController : Controller
    {
        Repositories.IEstateAgentRepository _estateagentRepository = null;
        
        public EstateAgentController(IEstateAgentRepository estateagentRepository)
        {
            _estateagentRepository = estateagentRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetByPage(int pageNumber, int pageSize)
        {
            List<DTO.EstateAgent>  estateagentList = null;
            int recordsTotal = 0;
            try
            {
                 estateagentList = _estateagentRepository.GetAll(pageNumber, pageSize);
                recordsTotal = _estateagentRepository. EstateAgentCount();
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
            return Json(new
            {
                recordsTotal,
                estateagentList
            });
        }

        public JsonResult GetAll()
        {
            List<EstateAgent> list = _estateagentRepository.GetAll();
            return Json(list.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetByID(int id)
        {
             var estateagent = _estateagentRepository.Get(id);
             return Json(new { estateagent = estateagent, success = true, errorMessage = "" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(int id)
        {
            var result = _estateagentRepository.Delete(id);

            return Json(new
            {
                success = result,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add( EstateAgent  estateagent)
        {
            int id = _estateagentRepository.Add( estateagent);

            return Json(new
            {
                success = id > 0 ? true : false,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Update( EstateAgent  estateagent)
        {
            bool result = _estateagentRepository.Update( estateagent);
            return Json(new
            {
                success = result,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

    }

}

WHMCAngularJS/Controllers/LandlordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using Repositories;
using WHMCAngularJS.ViewModel;

namespace WHMCAngularJs.Controllers
{
    public class LandlordController : Controller
    {
        Repositories.ILandlordRepository _landlordRepository = null;
        
        public LandlordController(ILandlordRepository landlordRepository)
        {
            _landlordRepository = landlordRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetByPage(int pageNumber, int pageSize)
        {
            List<DTO.Landlord>  landlordList = null;
            int recordsTotal = 0;
            try
            {
                 landlordList = _landlordRepository.GetAll(pageNumber, pageSize);
                recordsTotal = _landlordRepository. LandlordCount();
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
            return Json(new
            {
                recordsTotal,
                landlordList
            });
        }

        public JsonResult GetAll()
        {
            List<Landlord> list = _landlordRepository.GetAll();
            return Json(list.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetByID(int id)
        {
             var landlord = _landlordRepository.Get(id);
             return Json(new { landlord = landlord, success = true, errorMessage = "" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(int id)
        {
            var result = _landlordRepository.Delete(id);

            return Json(new
            {
                success = result,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add( Landlord  landlord)
        {
            int id = _landlordRepository.Add( landlord);

            return Json(new
            {
                success = id > 0 ? true : false,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Update( Landlord  landlord)
        {
            bool result = _landlordRepository.Update( landlord);
            return Json(new
            {
                success = result,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

    }

}

WHMCAngularJS/Controllers/OccupancyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using Repositories;
using WHMCAngularJS.ViewModel;

namespace WHMCAngularJs.Controllers
{
    public class OccupancyController : Controller
    {
        Repositories.IOccupancyRepository _occupancyRepository = null;
        Repositories.IOccupierRepository _occupierRepository = null;
        Repositories.IOccupancyNoteRepository _occupancyNoteRepository = null;

        public OccupancyController(IOccupancyRepository occupancyRepository, IOccupierRepository occupierRepository, IOccupancyNoteRepository occupancyNoteRepository)
        {
            _occupancyRepository = occupancyRepository;
            _occupierRepository = occupierRepository;
            _occupancyNoteRepository = occupancyNoteRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "WHMC Residential Management System";

            return View();
        }

        public JsonResult GetByPage(int pageNumber, int pageSize)
        {
            List<DTO.Occupancy> occupancyList = null;
            int recordsTotal = 0;
            try
            {
                occupancyList = _occupancyRepository.GetAll(pageNumber, pageSize);
                recordsTotal = _occupancyRepository.OccupancyCount();
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
            }
            return Json(new
            {
                recordsTotal,
                occupancyList
            });
        }

        public JsonResult GetAll()
        {
            List<Occupancy> list = _occupancyRepository.GetAll();
            return Json(list.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetByID(int id)
        {
            OccupancyViewModel model = new OccupancyViewModel();

            model.Occupancy = _occupancyRepository.Get(id);
            return Json(new { occupancy = model.Occupancy, success = true, errorMessage = "" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(int id)
        {
            OccupancyViewModel model = new OccupancyViewModel();

            var result = _occupancyRepository.Delete(id);

            return Json(new
            {
                success = result,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add(Occupancy occupancy)
        {
            int id = _occupancyRepository.Add(occupancy);

            return Json(new
            {
                success = id > 0 ? true : false,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Update(Occupancy occupancy)
        {
            bool result = _occupancyRepository.Update(occupancy);
            return Json(new
            {
                success = result,
                errorMessage = ""
            }, JsonRequestBehavior.AllowGet);
        }

    }

}

WHMCAngularJS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WHMC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href="~/Content/mg/package/angular-ui/grid.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-colorselector.min.css" rel="stylesheet" />

</head>
<body class="ng-cloak" ng-app="myapp">
    
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WHMC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>


            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/Home/Index" id="menu-toggle" style="float:right;">
                            <span class="fa fa-home" style="font-size:20px !Important;" aria-hidden="true"></span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Admin
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Occupancy")" class="">
                                <i class="fa a fa-users"></i>
                                <span>
                                    Occupancies
                                </span>
                            </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Apartment")" class="">
                                    <i class="fa fa-key"></i>
                                    <span>
                                        Apartments
                                    </span>
                                </a>
                            </li>
                            
                            <li>
                                <a href="@Url.Action("Index", "EstateAgent")" class="">
                                    <i class="fa fa-plug"></i>
                                    <span>
                                        Estate Agents
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Landlord")" class="">
                                    <i class="glyphicon glyphicon-user"></i>
                                    <span>
                                        Landlords
                                    </span>
                                </a>
                            </li>                            
                            <li>
                                <a href="@Url.Action("Index", "Occupier")" class="">
                                    <i class="fa fa-user"></i>
                                    <span>
                                        Occupiers
                                    </span>
                                </a>
                            
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "OccupierType")" class="">
                                    <i class="fa fa-cog"></i>
                                    <span>
                                        Occupier Types
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "ApartmentType")" class="">
                                    <i class="fa fa-cog"></i>
                                    <span>
                                        Apartment Types
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Archives
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Apartment</a></li>
                            <li><a href="#">Apartment Type</a></li>
                            <li><a href="#">Estate Agent</a></li>
                            <li><a href="#">Landlord</a></li>
                            <li><a href="#">Landlord</a></li>
                            <li><a href="#">Occupier</a></li>
                            <li><a href="#">Occupier Type</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Reports
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Vehicles</a></li>
                            <li><a href="#">Residents</a></li>
                            <li><a href="#">Landlords</a></li>
                            <li><a href="#">Estate Agents</a></li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("About", "About", "Home")</li>

                </ul>
                @*<ul class="nav navbar-nav navbar-right">

                        <li>
                            <span class="search">
                                <input type="text" class="form-control input-sm" maxlength="64" placeholder="Search" />
                                <button type="submit" class="searchbutton btn-secondary btn-sm"><span class="fa fa-search" style="font-size:20px !Important;" aria-hidden="true"></span></button>
                            </span>
                        </li>
                        <li>
                            <a href="#menu-toggle" id="menu-toggle" style="float:right;">
                                <span class="fa fa-bars" style="font-size:20px !Important;" aria-hidden="true"></span>
                            </a>
                        </li>

                    </ul>*@


                @Html.Partial("_LoginPartial")
            </div>


        </div>
        </nav>
        <div class="container body-content" style="margin-left: 0px">
            @RenderBody()

            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - WHMC Ltd</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/angular")
        @Scripts.Render("~/bundles/angularUIGrid")
        <script src="~/app/app.js"></script>
    <script src="~/Scripts/bootstrap-colorselector.min.js"></script>
        @RenderSection("scripts", required: false)
</body>
</html>